services:
  bot:
    build: .
    container_name: anticuss-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_PATH=/app/bot_data/data.db
    volumes:
      - ./bot_data:/app/bot_data